### PR TITLE
[GSOC-51] DAVE worlds and respective launch files

### PR DESCRIPTION
**Pull request by hmoyen**
This PR introduces two main features:

1. **World files**: 
   - New DAVE world files compatible with new Gazebo Harmonic, but still without plugins.
   - Some textures and models were replaced, and now all worlds import models from Fuel.

2. **ROS 2 Launch Files**: 
   - Launch files were added to `dave_demos` package, which call a world file in the `dave_worlds` package.

### CODE REVIEW

**Comment by woensug-choi** [comment]
@hmoyen Could we have more universal launch file using launch cobfigurationand arguments? 
examples are at examples/dave_demos/launch/model_in_empty_world.launch.py

also please append some readme yo examples/dave_demos/README about launching worlds.

**Comment by hmoyen** [comment]
@woensug-choi Sure! Will work on that

**Comment by hmoyen** [comment]
@woensug-choi Just added to the dave_demos README how to launch a world using a world_name argument

**Comment by woensug-choi** [comment]
Thank you for putting it all together. I've made modifications on it! Please check :) 
Also, could you make a ticket on Notion for issues at the bottom? We may not deal with it now but someday. 

## README
  - changed to launch ocean_waves as the first command to try since integrated world takes too long to launch at start (taking long time to download model files)
    - ros2 launch dave_demos dave_world.launch.py world_name:=`dave_ocean_waves`
  - Add description about downloading the files from https://app.gazebosim.org/

- Old sea surface removed (using brand new gazebo generic one)

## Worlds
  - Common Mods
    - Mod <physics> and remove <scene> tag mimicking https://github.com/gazebosim/docs/blob/master/harmonic/tutorials/sdf_worlds/world_demo.sdf and https://github.com/gazebosim/docs/blob/master/harmonic/tutorials/sensors/sensor_tutorial.sdf
    - Match world name
    - Format lint with XML formatter(default of VS Code)
    - Remove previous sea surface as we are adopting generic one
  - dave_ocean_waves
    - removed `ode` tag since it was causing warning that is unnecessary
  - dave_ocean_waves_transient_current
    - Kept. Need to add plugins later
  - dave_ocean_waves_occluded_bottom
    - Changed name to dave_ocean_waves_mossy_ground
  - dave_ocean_waves_dvl_current_profiling
    - Removed. Let's use `dave_ocean_waves_transient_current` and add dvl at the launch file with uploading the model there
  - dave_ocean_models
    - Manually defined GUI so that we can set initial position of the camera (I couldn't figure out just defining camera pose without all other GUI settings)
  - dave_new_bathy_example
    - it seems the Santorini_heightmap.tif have invalid coordinate system. (Could not open at https://app.geotiff.io/) The Volcano example of the gazebo (the volcano.tif at https://app.gazebosim.org/jennuine/fuel/models/Volcano) does load correctly at https://app.geotiff.io/
    - Removed the world hope we have time to investigate. Otherwise not including it.
  - dave_mud_occlusion_demo
    - Just removing it. seems to complex problem to GSoC
  - dave_graded_seabed
    - Removed BOP Panel
    - Rotated Heightmap and Changed light that equal to dave_ocean_waves
  - dave_electrical_mating
    - Adjusted positions and camera view angle
  - dave_bimanual_example
    - Reposition, add heightmap
  - dave_plug_and_socket_demo
    - renamed to `dave_plug_and_socket` 
    - Reposition, add heightmap
  - valve_manipulation
    - Removing it for now. (didn't see any useful models being loaded)
  - dave_Santorini
    - Rename to `dave_santorini`(small letters only)
    - Reposition and camera view angle set
  - dave_integrated
    - reposition and camera view angle set

## Issues
  - Plugin sdf warning
    - `Warning [Utils.cc:132] [/sdf/plugin[@name="gz::sim::systems::ShaderParam"]:<data-string>:L1]: XML Element[plugin], child of element[sdf], not defined in SDF. Copying[plugin] as children of [sdf]` when loading the models.
  - Better texture for default height map
    - Could we use https://fuel.gazebosim.org/1.0/OpenRobotics/models/Ocean Floor Texture (we can download files and apply and re-upload our heightmap)
  - Turbidity
    - https://app.gazebosim.org/mabelzhang/fuel/worlds/Multi-LRAUV%20Swimming%20Race
  - Recognizing coordiates of the GeoTiff
    - Santorini_heightmap.tif have invalid coordinate system. (Could not open at https://app.geotiff.io/) Gazebo complained about coordinate frame transformation. The Volcano example of the gazebo (the volcano.tif at https://app.gazebosim.org/jennuine/fuel/models/Volcano) does load correctly at https://app.geotiff.io/  and in Gazebo too.

**Pull request merged**
