### PR TITLE
[GSOC-52] Migration of rexov model

### PR DESCRIPTION
**Pull request by rakeshv24**
This PR introduces the migration of `rexrov` model. The following changes have been made:

1. Removed all `uuv_simulator` plugins.
2. Converted xacro and urdf model files to sdf.
3. Added `buoyancy`, `thruster`, and `hydrodynamic` plugins.
4. Tested in `dave_ocean_waves.world`

Note: The [added mass values](https://github.com/uuvsimulator/uuv_simulator/blob/bfb40cb153684a0703173117b6bbf4258e8e71c5/uuv_descriptions/urdf/rexrov.gazebo.xacro#L42) for the model do not seem correct and cause the simulation to crash. Therefore, we have used values of LRAUV in their place for the hydrodynamics plugin.

### CODE REVIEW

**Comment by woensug-choi** [comment]
## Initial position
- Rexrov starts half-way into the ground plane. setting initial z to `2.0` will spawn the rexrov in air and will drop due to the gravity

## <Limits> tag warning in joints
- Multiple warning of unrecognized tag in the joints.

  ```bash
  Warning [Utils.cc:132] [/sdf/model[@name="rexrov"]/joint[@name="thruster6_joint"]/limits:<data-string>:L465]: XML Element[limits], child of element[joint], not defined in SDF. Copying[limits] as children of [joint].
  ```
- It seems, it should be `<limit>` instead of `<limits>` and should be included within `<axis>` tag
   - https://github.com/gazebosim/gz-sim/blob/5641ef2cc7bed13e06892d29ffd3663b2f172e76/examples/worlds/sensors.sdf#L257-L267


## Imu sensor plugin not included model.sdf

   ```bash
   Warning [Utils.cc:132] [/sdf/model[@name="rexrov"]/sensor[@name="imu_sensor"]:<data-string>:L595]: XML Element[sensor], child of element[model], not defined in SDF. Copying[sensor] as children of [model].
   ```
   
to Fix, add below to model.sdf
    
   ```xml
    <plugin
      filename="gz-sim-imu-system"
      name="gz::sim::systems::Imu">
    </plugin>
   ```

## Added Mass
- Just to avoid using 0 values, let's use this (from LRAUV)

   ```xml
    <xDotU>-4.876161</xDotU>
    <yDotV>-126.324739</yDotV>
    <zDotW>-126.324739</zDotW>
    <kDotP>0</kDotP>
    <mDotQ>-33.46</mDotQ>
    <nDotR>-33.46</nDotR>
   ```

## Rexrov in dave_ocean_waves flip upside down when surfaced.
- As the center of gravity is too high to keep it straight, let's add values to bring it down

  ```xml
  # in model.sdf
   <link name="base_link">
      <inertial>
        <pose>0 0 -0.6 0 0 0</pose> # z value changed to -0.6
  ```

## Collision model
- Collision model doesn't seem to match with visual? was it this way on original dave too? Could we adjust little to match with the visual?
  - It especially looked strange since the collision model at the bottom is extended further out of the vehicle so that the rexrov would not touch ground. 
  
image

**Review by woensug-choi — CHANGES_REQUESTED** [review]
## Initial position
- for empty.world
   - Rexrov starts half-way into the ground plane. setting initial z to `2.0` will spawn the rexrov in air and will drop due to the gravity
- for ocean_waves
  - Could we initiate at `z=-5` to be able to see it from the beginning.

## <Limits> tag warning in joints
- Multiple warning of unrecognized tag in the joints.

  ```bash
  Warning [Utils.cc:132] [/sdf/model[@name="rexrov"]/joint[@name="thruster6_joint"]/limits:<data-string>:L465]: XML Element[limits], child of element[joint], not defined in SDF. Copying[limits] as children of [joint].
  ```
- It seems, it should be `<limit>` instead of `<limits>` and should be included within `<axis>` tag
   - https://github.com/gazebosim/gz-sim/blob/5641ef2cc7bed13e06892d29ffd3663b2f172e76/examples/worlds/sensors.sdf#L257-L267


## Imu sensor plugin not included model.sdf

   ```bash
   Warning [Utils.cc:132] [/sdf/model[@name="rexrov"]/sensor[@name="imu_sensor"]:<data-string>:L595]: XML Element[sensor], child of element[model], not defined in SDF. Copying[sensor] as children of [model].
   ```
   
to Fix, add below to model.sdf
    
   ```xml
    <plugin
      filename="gz-sim-imu-system"
      name="gz::sim::systems::Imu">
    </plugin>
   ```

## Added Mass
- Just to avoid using 0 values, let's use this (from LRAUV)

   ```xml
    <xDotU>-4.876161</xDotU>
    <yDotV>-126.324739</yDotV>
    <zDotW>-126.324739</zDotW>
    <kDotP>0</kDotP>
    <mDotQ>-33.46</mDotQ>
    <nDotR>-33.46</nDotR>
   ```

## Rexrov in dave_ocean_waves flip upside down when surfaced.
- As the center of gravity is too high to keep it straight, let's add values to bring it down

  ```xml
  # in model.sdf
   <link name="base_link">
      <inertial>
        <pose>0 0 -0.59 0 0 0</pose> # z value changed to -0.6
  ```

## Collision model
- Collision model doesn't seem to match with visual? was it this way on original dave too? Could we adjust little to match with the visual?
  - It especially looked strange since the collision model at the bottom is extended further out of the vehicle so that the rexrov would not touch ground. 
  
image

**Comment by rakeshv24** [comment]
@woensug-choi Thank you for the review! I have addressed all the comments.

## Imu sensor plugin not included model.sdf

The issue was not actually with the plugin as it already existed. Rather, I had to move the following snippet inside the link for `base_link`:

```bash
<sensor name="imu_sensor" type="imu">
  <always_on>true</always_on>
  <update_rate>1000.0</update_rate>
  <topic>imu</topic>
</sensor>
```

## Collision model

Yes, it was also defined this way on the original dave repo. However, after fixing the tag warnings, the collision model looks much better!

Screenshot from 2024-06-28 01-07-37

**Review by woensug-choi — APPROVED** [review]
Thank you! It all look good to me! Go ahead and merge!

**Pull request merged**
