### PR TITLE
[GSOC-52] Migration of Slocum Glider

### PR DESCRIPTION
**Pull request by rakeshv24**
This PR introduces the migration of Slocum glider model. The following changes have been made:

1. Removed all uuv_simulator plugins.
2. Converted xacro and urdf model files to sdf.
3. Added buoyancy, hydrodynamics, thruster, battery, joint_state_publisher, imu, and odometry plugins.
4. Tested in dave_ocean_waves.world.

Notes: 

1. The [added mass values](https://github.com/Field-Robotics-Lab/dave/blob/e54ea16bdaf7d6dbb466cf141846a03f284a44dd/models/dave_robot_models/models/glider_slocum/model.sdf#L150-L157) for the model do not seem correct and cause the simulation to crash. Therefore, we have used nil values in their place for the hydrodynamics plugin.
2. Rebasing is required after [[GSOC-62] Added buoyancy plugin to the world files](https://github.com/IOES-Lab/dave/pull/7) is merged with `ros2` branch.

### CODE REVIEW

**Comment by rakeshv24** [comment]
@hmoyen, @GauravKumar9920, @abhimanyubhowmik can you pull this branch and try examples 3 and 4 mentioned [here](https://github.com/IOES-Lab/dave/blob/glider-slocum/examples/dave_robot_launch/README.md#4-launching-slocum-glider-in-dave_ocean_wavesworld)?

**Review by GauravKumar9920 — APPROVED** [review]

**Comment by hmoyen** [comment]
Looks fine to me as well :)

**Comment by woensug-choi** [comment]
@rakeshv24 Added a initial position mod to have the glider in the scene bit longer. All look good to me too!

**Comment by rakeshv24** [comment]
Awesome!

**Review by woensug-choi — APPROVED** [review]
Good to go

**Comment by rakeshv24** [comment]
@woensug-choi I'll merge this after rebasing it with the other PR I opened.

**Pull request merged**
