### PR TITLE
[GSOC-67] Migration of USBL plugins

### PR DESCRIPTION
**Pull request by hmoyen**
This PR introduces three main features:

1. **USBL Plugins:**
   - **Transceiver Plugin:** Compatible with ROS 2 and Harmonic.
   - **Transponder Plugin:** Compatible with ROS 2 and Harmonic.

2. **Tutorial World:**
   - Added `usbl_tutorial.world` to demonstrate the usage of the new USBL plugins.

3. **World Launch File:**
   - Included a verbose argument to enable monitoring of the plugin's Gazebo messages.

Documentation on how to use the plugin is here: [Documentation](https://yeongdocat.notion.site/Usbl-Migration-eccc26dce0e54b24b32f55182eb28336)

### CODE REVIEW

**Comment by hmoyen** [comment]
@woensug-choi The pre-commit seems to be failing due to `/usr/bin/env: ament_cppcheck: No such file or directory` and `Executable ament_cpplint not found` .  I am not so familiar with pre-commit, but could it be some configuration that is missing in github workflows?

**Comment by woensug-choi** [comment]
Try
```
pip3 install pre-commit && pre-commit install && pre-commit run --all-files
```
oh.. didn't work on my side too. I may caued this. ignore it for now

**Comment by woensug-choi** [comment]
@hmoyen 

- Wouldn't setting the channel mean individual mode?
Is is correct that when channel is fixed to one transponder `ros2 topic pub --once /USBL/transceiver_manufacturer_168/channel_switch std_msgs/String "data: '1'"` will implicitly mean that the user is using `individual` mode? Initiated at `common` mode and setting `channel_switch` to `data: '1' still printed every transponder data.

- If having individual mode, then the transceiver should be able to recognize different transponder signals?
If so, shouldn't we need to add `transponder name` on `transponder_location` msg?

**Comment by hmoyen** [comment]
@woensug-choi here are the changes made:

- `Location.msg` was created to include transponder_id in the location topic messages.
- If attempting to use the individual ping topic without being in individual mode, it won't respond. Gazebo will indicate that individual mode isn't set.
- Requesting a channel switch automatically changes the mode to individual.

**Comment by woensug-choi** [comment]
```bash
ros2 topic echo /USBL/transceiver_manufacturer_168/transponder_location
```
returned
```bash
The message type 'dave_interfaces/msg/Location' is invalid
```

**Comment by hmoyen** [comment]
@woensug-choi It used to happen for me too when I did not `source install/setup.bash` (dave's workspace) in the current terminal.

**Pull request merged**
