### PR TITLE
Ardusub install

### LINKED ISSUE #19: Failed to load ArduPilot plugin for BlueROV2 model
## Issue Summary

The ArduPilot plugin is not loading correctly when testing the BlueROV2 model in the Docker environment. We need to resolve this error to ensure proper functionality.

## Details

1. The BlueROV2 models have been added, but the ArduPilot plugin does not load properly — `[Err] [SystemLoader.cc:92] Failed to load system plugin [libArduPilotPlugin.so]: Could not find shared library.`
2. The `ardupilot` and `ardupilot_gazebo` are installed in the Docker image at `/opt/ardupilot_dave/` in an attempt to resolve the above error.

## Conversation Summary

1. Prerequisites such as `libgz-sim8-dev`, `rapidjson-dev`, `libopencv-dev`, and `gstreamer` are also required and need to be added to the installation script.
2. Further testing has shown that`mavros` is needed, and possibly `mavros_extra_plugins` as well.
3. The USER permissions on the Docker image for Mac are incorrect, and ROS2 is not sourced upon startup.

### Step 1: Pull the recent docker image

**For Ubuntu:**
```
docker pull ioeslab/dave:ros2
docker tag ioeslab/dave:ros2 dave:latest
source ~/dave_ws/dave_venv/bin/activate
cd ~/dave_ws/src/dockwater
./run.bash dave:latest
```

**For Mac:**
```
docker pull ioeslab/dave:ros2-arm-rdp
docker tag ioeslab/dave:ros2-arm-rdp dave:latest
source ~/dave_ws/dave_venv/bin/activate
cd ~/dave_ws/src/dockwater
./run.bash -r dave:latest
```

### Step 2: Launch BlueROV2 model

```cd ~/dave_ws/src/dave
git checkout robot_launch
cd ~/dave_ws
colcon build && source install/setup.bash
ros2 launch dave_demos dave_robot.launch.py z:=-5 namespace:=bluerov2 world_name:=dave_ocean_waves paused:=false
```

### PR DESCRIPTION
**Pull request by woensug-choi**
PR for new baseline docker image to resolve https://github.com/IOES-Lab/dave/issues/19

## What's been added
- Ardupilot and Ardusub install from source at `/opt/ardupilot_dave`
- Mavros install from source at `/opt/mavros`

## Image is being built from `dockertest` branch
- Github action is only set to run on `ros2` and `dockertest`. The latest update of this branch is merged to `dockertest` which triggered the Github CI build using self-hosted runner (a local linux machine in my lab). It may take upto 24 hours for full ARM and AMD build.
  - Below badges are targeted to `dockertest` branch. It will show `failing` until action is done. Check `Actions` tab on top.
  - [Publish a Docker image (AMD64; Common X86_64 Linux Machine)](https://github.com/IOES-Lab/dave/actions/workflows/docker-amd64.yml)
  - [Publish a Docker image (ARM64; Apple Silicon)](https://github.com/IOES-Lab/dave/actions/workflows/docker-arm64v8.yml)

## To-do before merge to `ros2`
- Change branch name from `ardusub_install` to `$BRANCH` at
  - https://github.com/IOES-Lab/dave/blob/f91e807850937bd5d0ffcaa94cf0a2de4dac99d2/.docker/jazzy.amd64.dockerfile#L57
  - https://github.com/IOES-Lab/dave/blob/f91e807850937bd5d0ffcaa94cf0a2de4dac99d2/.docker/jazzy.amd64.dockerfile#L61
  - https://github.com/IOES-Lab/dave/blob/f91e807850937bd5d0ffcaa94cf0a2de4dac99d2/.docker/jazzy.arm64v8.dockerfile#L108
  - https://github.com/IOES-Lab/dave/blob/f91e807850937bd5d0ffcaa94cf0a2de4dac99d2/.docker/jazzy.arm64v8.dockerfile#L112
  - https://github.com/IOES-Lab/dave/blob/f91e807850937bd5d0ffcaa94cf0a2de4dac99d2/extras/mavros-ubuntu-install.sh#L21-L22

### CODE REVIEW

**Comment by woensug-choi** [comment]
@rakeshv24 Pinging you that the image `ioeslab/dave:ros2` for amd64 and `ioeslab/dave:ros2-arm-rdp` for apple silicon is ready to test.

**Comment by rakeshv24** [comment]
Will test it soon!

**Comment by rakeshv24** [comment]
@woensug-choi I tested `ioeslab/dave:ros2-arm-rdp` and it works fine! Since I don't have access to an ubuntu machine currently, I couldn't test the other image.

**Comment by woensug-choi** [comment]
@rakeshv24 Lovely! 👍

**Comment by woensug-choi** [comment]
@rakeshv24 new `ioeslab/dave:ros2-arm-rdp` is up! I've tested `sim_vehicle.py -L RATBeach -v ArduSub -f vectored --model=JSON --out=udp:0.0.0.0:14550 --console` and shows console window just fine.

Also pushed `ioeslab/dave:ros2` for `amd` machines. I've decided to run the docker image as `root` user. This modification is made at `ioeslab/dockwater` repository.
- Reasonings
   - It was particularly tricky since the `rocker-dockwater` mounts the host machines user when running it. Unable to install ardupilot in user space. If I were to use custom user (e.g. `docker` as the case in rdp of arm), the x11 windows doesn't show on dockwater.

**Comment by woensug-choi** [comment]
If we were to use `mavros-extras` package, I saw some errors relating YAML.
I've found https://github.com/mavlink/mavros/issues/1960 and https://github.com/mavlink/mavros/pull/1988. I've tested and found that the evan's PR did fix it. At the moment, we are using `5884e2f5010cc811398d92eddede9b0c7454e68a` commit (which happend 5 days ago) in the https://github.com/IOES-Lab/dave/blob/b77235dac5655e5b1f8045f3c10456ec17820d98/extras/repos/mavros.jazzy.repos#L5 instead of `2.8.0` (that of the latest release). We may need to change it later to official release version.

**Comment by rakeshv24** [comment]
We need to fix and merge this PR as well @woensug-choi

**Comment by woensug-choi** [comment]
@rakeshv24 You mean fixing branch names in dockerfile and install script right? Does the functionality you intended using ardusub work? or are we postponding ardusub functions to ver 1.1?

**Comment by rakeshv24** [comment]
@woensug-choi yes that is what I meant (changing branch names in docker file and installation scripts). Also, the functionality I intended works fine. In this version, the bluerov models will be launched with ardusub process. In later releases, we will target advanced functionality.

**Pull request merged**
